version: '3.9'

services:
  trackingdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "5532:1433"
    networks:
      - mynetwork
  triage:
    image: triageapi
    build:
      context: .
      dockerfile: src/Triage.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - trackingdb
    networks:
      - mynetwork
  webapp:
    image: trackingchainwebapp
    build:
      context: .
      dockerfile: src/TrackingChain.WebApp/Dockerfile
    ports:
      - "12345:12345"
    depends_on:
      - triage
    networks:
      - mynetwork
  aggregator-pool:
    image: aggregatorpoolworker
    build:
      context: .
      dockerfile: src/AggregatorPool.Worker/Dockerfile
    depends_on:
      - webapp
    networks:
      - mynetwork
  transaction-generator:
    image: transactiongeneratorworker
    build:
      context: .
      dockerfile: src/TransactionGenerator.Worker/Dockerfile
    depends_on:
      - aggregator-pool
    networks:
      - mynetwork
  transaction-watcher:
    image: transactionwatcherworker
    build:
      context: .
      dockerfile: src/TransactionWatcher.Worker/Dockerfile
    depends_on:
      - transaction-generator
    networks:
      - mynetwork
  monitor:
    image: monitor
    build:
      context: .
      dockerfile: src/TransactionMonitor.Worker/Dockerfile
    depends_on:
      - transaction-watcher
    networks:
      - mynetwork
networks:
  mynetwork:
