version: '3.9'

services:
  trackingdb:
    image: fedec87p/trackingdb:devm2
    environment:
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "5532:1433"
    networks:
      - mynetwork
  triage:
    image: fedec87p/triageapi:latest
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - trackingdb
    networks:
      - mynetwork
  webapp:
    image: fedec87p/trackingchainwebapp:latest
    ports:
      - "12345:12345"
    depends_on:
      - triage
    networks:
      - mynetwork
  aggregator-pool:
    image: fedec87p/aggregatorpool:latest
    depends_on:
      - triage
    networks:
      - mynetwork
  transaction-generator:
    image: fedec87p/transactiongenerator:latest
    depends_on:
      - triage
    networks:
      - mynetwork
  transaction-watcher:
    image: fedec87p/transactionwatcher:latest
    depends_on:
      - triage
    networks:
      - mynetwork
networks:
  mynetwork:
