version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    expose:
      - 1433
    environment:
      SA_PASSWORD: "T5snGs!d98Sm&"
      ACCEPT_EULA: "Y"
  triageapi:
    image: ${DOCKER_REGISTRY-}triageapi
    ports:
      - 5001:80
      - 5002:443
    build:
      context: .
      dockerfile: src/TriageAPI/Dockerfile
    depends_on:
      - "sql-server-db"
  aggregatorpoolworker:
    image: ${DOCKER_REGISTRY-}aggregatorpoolworker
    build:
      context: .
      dockerfile: src/AggregatorPoolWorker/Dockerfile
    depends_on:
      - "triageapi"
  transactiongeneratorworker:
    image: ${DOCKER_REGISTRY-}transactiongeneratorworker
    build:
      context: .
      dockerfile: src/TransactionGeneratorWorker/Dockerfile
    depends_on:
      - "triageapi"
  transactionwatcherworker:
    image: ${DOCKER_REGISTRY-}transactionwatcherworker
    build:
      context: .
      dockerfile: src/TransactionWatcherWorker/Dockerfile
    depends_on:
      - "triageapi"
  triagewebapplication:
    image: ${DOCKER_REGISTRY-}triagewebapplication
    ports:
      - 5101:80
      - 5102:443
    build:
      context: .
      dockerfile: src/TriageWebApplication/Dockerfile
    depends_on:
      - "triageapi"
