//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Substrate.ContractRococo.NET.NetApiExt.Generated.Types.Base;

namespace TrackingChain.Core.Clients
{
    public interface IAccountId32
    {
        IArr32U8 Value { get; set; }

        void Decode(byte[] byteArray, ref int p);
        byte[] Encode();
        string TypeName();
    }
}