//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi.Model.Types.Primitive;

namespace Substrate.ContractRococo.NET.NetApiExt.Generated.Types.Base
{
    public interface IArr32U8
    {
        int TypeSize { get; }
        U8[] Value { get; set; }

        void Create(U8[] array);
        void Decode(byte[] byteArray, ref int p);
        byte[] Encode();
        string TypeName();
    }
}