# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore Triage.API dependencies
      run: dotnet restore src/Triage.API/Triage.API.csproj
    - name: Restore AggregatorPool.Worker dependencies
      run: dotnet restore src/AggregatorPool.Worker/AggregatorPool.Worker.csproj
    - name: Restore TransactionGenerator.Worker dependencies
      run: dotnet restore src/TransactionGenerator.Worker/TransactionGenerator.Worker.csproj
    - name: Restore TransactionWatcher.Worker dependencies
      run: dotnet restore src/TransactionWatcher.Worker/TransactionWatcher.Worker.csproj
    - name: Restore TrackingChain.WebApplication dependencies
      run: dotnet restore src/TrackingChain.WebApplication/TrackingChain.WebApplication.csproj
    - name: Restore TransactionGeneratorCore.Tests dependencies
      run: dotnet restore test/TrackingChain.UnitTest/TrackingChain.UnitTest.csproj

    - name: Build Triage.API
      run: dotnet build src/Triage.API/Triage.API.csproj --no-restore
    - name: Build AggregatorPool.Worker
      run: dotnet build src/AggregatorPool.Worker/AggregatorPool.Worker.csproj --no-restore
    - name: Build TransactionGenerator.Worker
      run: dotnet build src/TransactionGenerator.Worker/TransactionGenerator.Worker.csproj --no-restore
    - name: Build TransactionWatcher.Worker
      run: dotnet build src/TransactionWatcher.Worker/TransactionWatcher.Worker.csproj --no-restore
    - name: Build TrackingChain.WebApplication
      run: dotnet build src/TrackingChain.WebApplication/TrackingChain.WebApplication.csproj --no-restore
    - name: Build TrackingChain.UnitTest
      run: dotnet build test/TrackingChain.UnitTest/TrackingChain.UnitTest.csproj --no-restore

    - name: Test TrackingChain.UnitTest
      run: dotnet test test/TrackingChain.UnitTest/TrackingChain.UnitTest.csproj --no-build --verbosity normal
